#!/usr/bin/env bash


# Create loin config (should pass as args later)

CONF=loin.conf
if [ ! -f $CONF ]
then
    touch $CONF
    echo "bind_port=4444" >> $CONF
    echo "lnd_address=\"https://lightning_lnd_1:$LND_GRPC_PORT\"" >> $CONF
    # echo "lnd_address=\"https://$DEVICE_DOMAIN_NAME:$LND_GRPC_PORT\"" >> $CONF
    echo "lnd_cert_path=\"$TLS_FILE\"" >> $CONF
    echo "lnd_macaroon_path=\"$MACAROON_FILE\"" >> $CONF
fi

cat loin.conf
loin --conf loin.conf 1 038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5@144.76.24.71:9735 1000000


# loin --bind-port=4444 --lnd-address=https://lightning_lnd_1:$LND_GRPC_PORT --lnd-cert-path=$TLS_FILE --lnd-macaroon-path=$MACAROON_FILE 1 038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5@144.76.24.71:9735 1000000


echo "STOPPED RUNNING LOIN"
