version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/reverse-https-proxy.conf:/etc/nginx/nginx.conf"
      - "./nginx/ssl:/etc/ssl"
    ports:
      - "3010:3010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
