name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: docker
      run: docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}'
    - name: ip
      run: ip addr show | grep "\binet\b.*\bdocker0\b" | awk '{print $2}' | cut -d '/' -f 1
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '2.10.2'
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --nocapture
    - name: Log nginx
      run: |
        cat /var/log/nginx/access.log
        cat /var/log/nginx/error.log
